//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housemate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyRecord
    {
        public int br { get; set; }
        public Nullable<int> history_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> service_id { get; set; }
    
        public virtual BuyHistory BuyHistory { get; set; }
        public virtual Product Product { get; set; }
        public virtual Service Service { get; set; }
    }
}
