//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housemate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLogin
    {
        public int login_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
    }
}
