//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housemate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderRecords = new HashSet<OrderRecord>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string order_status { get; set; }
        public string feedback { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> cart_id { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRecord> OrderRecords { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
