//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housemate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public int payment_method_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string card_number { get; set; }
        public string cardholder_name { get; set; }
        public string expiration_date { get; set; }
        public string cvv { get; set; }
        public Nullable<bool> is_default { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
    }
}
