//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housemate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int report_id { get; set; }
        public string customer_email { get; set; }
        public string report_subject { get; set; }
        public string report_details { get; set; }
        public Nullable<System.DateTime> report_date { get; set; }
        public string customer_name { get; set; }
        public string customer_contact { get; set; }
    }
}
